$(function () {
    //Reference the autogenerated SignalR hub script.
    $.getScript("http://localhost:8020/signalr/hubs", function (script, textStatus) {
        //Set the hubs URL for the connection
        $.connection.hub.url = "http://localhost:8020/signalr";

        // Declare a proxy to reference the hub.
        var cnnVessel = $.connection.vesselHub;

        $.connection.hub.start()
            .done(function () {
                var group = $('#groupList').val();
                cnnVessel.server.join(group);
                cnnVessel.lastGroup = group;
            })
            .fail(function () {
                setOffLine();
            });

        $('#btnConenct').click(function () {
            $('#message').text('Connecting to ' + $('#groupList').val() + ' ...');
            setTimeout(function () {
                if ($.connection.hub.state === 1) {
                    var group = $('#groupList').val();
                    cnnVessel.server.removeGroup(cnnVessel.lastGroup);
                    cnnVessel.server.join(group);
                    cnnVessel.lastGroup = group;
                } else {
                    connect()
                }
            }, 1000)

        });

        function connect() {
            $.connection.hub.start()
                .done(function () {
                    $('#message').text('Done!');
                }).fail(function () {
                    setOffLine();
                });
        }

        // Create a function that the hub can call to broadcast messages.
        cnnVessel.client.addMessage = function (message) {
            console.log('Notification received for group ' + $('#groupList').val() + ' at time ' + new Date().toJSON());
            var resultString = JSON.parse(message);
            var result = JSON.parse(resultString);
            var store = new dojo.data.ItemFileWriteStore({ data: { items: result.Data } });
            grid.setStore(store);
            localStorage.setItem("localData", resultString);
        }


    })
        .fail(function (jqxhr, settings, exception) {
            setOffLine();
        });

    function setOffLine() {
        var data = JSON.parse(localStorage.getItem("localData"));
        var store = new dojo.data.ItemFileWriteStore({ data: { items: data.Data } });
        grid.setStore(store);
        $('#btnConenct').addClass('disabled');
        $('#btnConenct').text('Off Line');
    }
});